# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from extended_object_detection/ComplexObjectArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import extended_object_detection.msg
import geometry_msgs.msg
import std_msgs.msg

class ComplexObjectArray(genpy.Message):
  _md5sum = "fad960a5713d3b6fcdee1446c3f9b0ff"
  _type = "extended_object_detection/ComplexObjectArray"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
extended_object_detection/ComplexObject[] complex_objects

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: extended_object_detection/ComplexObject
int32 type_id                                       # id of object type, according to ObjectBase
string type_name                                    # name of object type, according to ObjectBase

float64 score                                       # confidence coefficient of current result
extended_object_detection/Rect rect                 # object frames on image and 3d coordinates
geometry_msgs/Transform transform                   # transform to object center in meters, if z=1 distance is unknow, only direction
extended_object_detection/SimpleObject[] objects    # set of simple objects form current complex

================================================================================
MSG: extended_object_detection/Rect
extended_object_detection/ImagePoint left_bottom
extended_object_detection/ImagePoint right_up
geometry_msgs/Vector3[] cornerTranslates    # translate to rect corners, from bottom left in clock-wice direction, if z value is 1, it means that it is unit vector in homogeneous coordnates 


================================================================================
MSG: extended_object_detection/ImagePoint
int32 x
int32 y

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Transform
# This represents the transform between two coordinate frames in free space.

Vector3 translation
Quaternion rotation

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: extended_object_detection/SimpleObject
# object info
int32 type_id                               # id of type, corresponded to object base
string type_name                            # name of type, corresponded to object base
float64 score                               # confidence coefficient of current result
extended_object_detection/ExtractedInfo[] extracted_info

# object position and geometry
geometry_msgs/Transform transform           # transform to object center
extended_object_detection/Rect rect         # object frames on image and 3d coordinates
extended_object_detection/Contour contour   # contour image and 3d info

# tracking
extended_object_detection/Track track       # information about tracking if it is enabled





================================================================================
MSG: extended_object_detection/ExtractedInfo
int32 sub_id
string text

================================================================================
MSG: extended_object_detection/Contour
extended_object_detection/ImagePoint[] image_points   # points on image
geometry_msgs/Vector3[] contourTranslates             # translations to contour points

================================================================================
MSG: extended_object_detection/Track
uint8 DETECTED = 1  # Current result is obtained by detector
uint8 TRACKED = 2  # Current result is obtained by opencv tracker
uint8 LOST = 3      # Failed to obtain result, this is last saved

int32 id            # track unique id (in group of one object)
uint8 status        # status described above
#extended_object_detection/ImagePoint[] image_point_history
#geometry_msgs/Transform[] transform_history
"""
  __slots__ = ['header','complex_objects']
  _slot_types = ['std_msgs/Header','extended_object_detection/ComplexObject[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,complex_objects

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComplexObjectArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.complex_objects is None:
        self.complex_objects = []
    else:
      self.header = std_msgs.msg.Header()
      self.complex_objects = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.complex_objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.complex_objects:
        _x = val1.type_id
        buff.write(_get_struct_i().pack(_x))
        _x = val1.type_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.score
        buff.write(_get_struct_d().pack(_x))
        _v1 = val1.rect
        _v2 = _v1.left_bottom
        _x = _v2
        buff.write(_get_struct_2i().pack(_x.x, _x.y))
        _v3 = _v1.right_up
        _x = _v3
        buff.write(_get_struct_2i().pack(_x.x, _x.y))
        length = len(_v1.cornerTranslates)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.cornerTranslates:
          _x = val3
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v4 = val1.transform
        _v5 = _v4.translation
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = _v4.rotation
        _x = _v6
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        length = len(val1.objects)
        buff.write(_struct_I.pack(length))
        for val2 in val1.objects:
          _x = val2.type_id
          buff.write(_get_struct_i().pack(_x))
          _x = val2.type_name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.score
          buff.write(_get_struct_d().pack(_x))
          length = len(val2.extracted_info)
          buff.write(_struct_I.pack(length))
          for val3 in val2.extracted_info:
            _x = val3.sub_id
            buff.write(_get_struct_i().pack(_x))
            _x = val3.text
            length = len(_x)
            if python3 or type(_x) == unicode:
              _x = _x.encode('utf-8')
              length = len(_x)
            buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _v7 = val2.transform
          _v8 = _v7.translation
          _x = _v8
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v9 = _v7.rotation
          _x = _v9
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v10 = val2.rect
          _v11 = _v10.left_bottom
          _x = _v11
          buff.write(_get_struct_2i().pack(_x.x, _x.y))
          _v12 = _v10.right_up
          _x = _v12
          buff.write(_get_struct_2i().pack(_x.x, _x.y))
          length = len(_v10.cornerTranslates)
          buff.write(_struct_I.pack(length))
          for val4 in _v10.cornerTranslates:
            _x = val4
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v13 = val2.contour
          length = len(_v13.image_points)
          buff.write(_struct_I.pack(length))
          for val4 in _v13.image_points:
            _x = val4
            buff.write(_get_struct_2i().pack(_x.x, _x.y))
          length = len(_v13.contourTranslates)
          buff.write(_struct_I.pack(length))
          for val4 in _v13.contourTranslates:
            _x = val4
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v14 = val2.track
          _x = _v14
          buff.write(_get_struct_iB().pack(_x.id, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.complex_objects is None:
        self.complex_objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.complex_objects = []
      for i in range(0, length):
        val1 = extended_object_detection.msg.ComplexObject()
        start = end
        end += 4
        (val1.type_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.type_name = str[start:end]
        start = end
        end += 8
        (val1.score,) = _get_struct_d().unpack(str[start:end])
        _v15 = val1.rect
        _v16 = _v15.left_bottom
        _x = _v16
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
        _v17 = _v15.right_up
        _x = _v17
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v15.cornerTranslates = []
        for i in range(0, length):
          val3 = geometry_msgs.msg.Vector3()
          _x = val3
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v15.cornerTranslates.append(val3)
        _v18 = val1.transform
        _v19 = _v18.translation
        _x = _v19
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v20 = _v18.rotation
        _x = _v20
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.objects = []
        for i in range(0, length):
          val2 = extended_object_detection.msg.SimpleObject()
          start = end
          end += 4
          (val2.type_id,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.type_name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.type_name = str[start:end]
          start = end
          end += 8
          (val2.score,) = _get_struct_d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.extracted_info = []
          for i in range(0, length):
            val3 = extended_object_detection.msg.ExtractedInfo()
            start = end
            end += 4
            (val3.sub_id,) = _get_struct_i().unpack(str[start:end])
            start = end
            end += 4
            (length,) = _struct_I.unpack(str[start:end])
            start = end
            end += length
            if python3:
              val3.text = str[start:end].decode('utf-8', 'rosmsg')
            else:
              val3.text = str[start:end]
            val2.extracted_info.append(val3)
          _v21 = val2.transform
          _v22 = _v21.translation
          _x = _v22
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v23 = _v21.rotation
          _x = _v23
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v24 = val2.rect
          _v25 = _v24.left_bottom
          _x = _v25
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
          _v26 = _v24.right_up
          _x = _v26
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          _v24.cornerTranslates = []
          for i in range(0, length):
            val4 = geometry_msgs.msg.Vector3()
            _x = val4
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            _v24.cornerTranslates.append(val4)
          _v27 = val2.contour
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          _v27.image_points = []
          for i in range(0, length):
            val4 = extended_object_detection.msg.ImagePoint()
            _x = val4
            start = end
            end += 8
            (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
            _v27.image_points.append(val4)
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          _v27.contourTranslates = []
          for i in range(0, length):
            val4 = geometry_msgs.msg.Vector3()
            _x = val4
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            _v27.contourTranslates.append(val4)
          _v28 = val2.track
          _x = _v28
          start = end
          end += 5
          (_x.id, _x.status,) = _get_struct_iB().unpack(str[start:end])
          val1.objects.append(val2)
        self.complex_objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.complex_objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.complex_objects:
        _x = val1.type_id
        buff.write(_get_struct_i().pack(_x))
        _x = val1.type_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.score
        buff.write(_get_struct_d().pack(_x))
        _v29 = val1.rect
        _v30 = _v29.left_bottom
        _x = _v30
        buff.write(_get_struct_2i().pack(_x.x, _x.y))
        _v31 = _v29.right_up
        _x = _v31
        buff.write(_get_struct_2i().pack(_x.x, _x.y))
        length = len(_v29.cornerTranslates)
        buff.write(_struct_I.pack(length))
        for val3 in _v29.cornerTranslates:
          _x = val3
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v32 = val1.transform
        _v33 = _v32.translation
        _x = _v33
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v34 = _v32.rotation
        _x = _v34
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        length = len(val1.objects)
        buff.write(_struct_I.pack(length))
        for val2 in val1.objects:
          _x = val2.type_id
          buff.write(_get_struct_i().pack(_x))
          _x = val2.type_name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.score
          buff.write(_get_struct_d().pack(_x))
          length = len(val2.extracted_info)
          buff.write(_struct_I.pack(length))
          for val3 in val2.extracted_info:
            _x = val3.sub_id
            buff.write(_get_struct_i().pack(_x))
            _x = val3.text
            length = len(_x)
            if python3 or type(_x) == unicode:
              _x = _x.encode('utf-8')
              length = len(_x)
            buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _v35 = val2.transform
          _v36 = _v35.translation
          _x = _v36
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v37 = _v35.rotation
          _x = _v37
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v38 = val2.rect
          _v39 = _v38.left_bottom
          _x = _v39
          buff.write(_get_struct_2i().pack(_x.x, _x.y))
          _v40 = _v38.right_up
          _x = _v40
          buff.write(_get_struct_2i().pack(_x.x, _x.y))
          length = len(_v38.cornerTranslates)
          buff.write(_struct_I.pack(length))
          for val4 in _v38.cornerTranslates:
            _x = val4
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v41 = val2.contour
          length = len(_v41.image_points)
          buff.write(_struct_I.pack(length))
          for val4 in _v41.image_points:
            _x = val4
            buff.write(_get_struct_2i().pack(_x.x, _x.y))
          length = len(_v41.contourTranslates)
          buff.write(_struct_I.pack(length))
          for val4 in _v41.contourTranslates:
            _x = val4
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v42 = val2.track
          _x = _v42
          buff.write(_get_struct_iB().pack(_x.id, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.complex_objects is None:
        self.complex_objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.complex_objects = []
      for i in range(0, length):
        val1 = extended_object_detection.msg.ComplexObject()
        start = end
        end += 4
        (val1.type_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.type_name = str[start:end]
        start = end
        end += 8
        (val1.score,) = _get_struct_d().unpack(str[start:end])
        _v43 = val1.rect
        _v44 = _v43.left_bottom
        _x = _v44
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
        _v45 = _v43.right_up
        _x = _v45
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v43.cornerTranslates = []
        for i in range(0, length):
          val3 = geometry_msgs.msg.Vector3()
          _x = val3
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v43.cornerTranslates.append(val3)
        _v46 = val1.transform
        _v47 = _v46.translation
        _x = _v47
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v48 = _v46.rotation
        _x = _v48
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.objects = []
        for i in range(0, length):
          val2 = extended_object_detection.msg.SimpleObject()
          start = end
          end += 4
          (val2.type_id,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.type_name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.type_name = str[start:end]
          start = end
          end += 8
          (val2.score,) = _get_struct_d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.extracted_info = []
          for i in range(0, length):
            val3 = extended_object_detection.msg.ExtractedInfo()
            start = end
            end += 4
            (val3.sub_id,) = _get_struct_i().unpack(str[start:end])
            start = end
            end += 4
            (length,) = _struct_I.unpack(str[start:end])
            start = end
            end += length
            if python3:
              val3.text = str[start:end].decode('utf-8', 'rosmsg')
            else:
              val3.text = str[start:end]
            val2.extracted_info.append(val3)
          _v49 = val2.transform
          _v50 = _v49.translation
          _x = _v50
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v51 = _v49.rotation
          _x = _v51
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v52 = val2.rect
          _v53 = _v52.left_bottom
          _x = _v53
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
          _v54 = _v52.right_up
          _x = _v54
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          _v52.cornerTranslates = []
          for i in range(0, length):
            val4 = geometry_msgs.msg.Vector3()
            _x = val4
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            _v52.cornerTranslates.append(val4)
          _v55 = val2.contour
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          _v55.image_points = []
          for i in range(0, length):
            val4 = extended_object_detection.msg.ImagePoint()
            _x = val4
            start = end
            end += 8
            (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
            _v55.image_points.append(val4)
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          _v55.contourTranslates = []
          for i in range(0, length):
            val4 = geometry_msgs.msg.Vector3()
            _x = val4
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            _v55.contourTranslates.append(val4)
          _v56 = val2.track
          _x = _v56
          start = end
          end += 5
          (_x.id, _x.status,) = _get_struct_iB().unpack(str[start:end])
          val1.objects.append(val2)
        self.complex_objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_iB = None
def _get_struct_iB():
    global _struct_iB
    if _struct_iB is None:
        _struct_iB = struct.Struct("<iB")
    return _struct_iB
