// Generated by gencpp from file extended_object_detection/SetSimpleObjects.msg
// DO NOT EDIT!


#ifndef EXTENDED_OBJECT_DETECTION_MESSAGE_SETSIMPLEOBJECTS_H
#define EXTENDED_OBJECT_DETECTION_MESSAGE_SETSIMPLEOBJECTS_H

#include <ros/service_traits.h>


#include <extended_object_detection/SetSimpleObjectsRequest.h>
#include <extended_object_detection/SetSimpleObjectsResponse.h>


namespace extended_object_detection
{

struct SetSimpleObjects
{

typedef SetSimpleObjectsRequest Request;
typedef SetSimpleObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSimpleObjects
} // namespace extended_object_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::extended_object_detection::SetSimpleObjects > {
  static const char* value()
  {
    return "7e842254cbe0d0dd775c05000053aba0";
  }

  static const char* value(const ::extended_object_detection::SetSimpleObjects&) { return value(); }
};

template<>
struct DataType< ::extended_object_detection::SetSimpleObjects > {
  static const char* value()
  {
    return "extended_object_detection/SetSimpleObjects";
  }

  static const char* value(const ::extended_object_detection::SetSimpleObjects&) { return value(); }
};


// service_traits::MD5Sum< ::extended_object_detection::SetSimpleObjectsRequest> should match
// service_traits::MD5Sum< ::extended_object_detection::SetSimpleObjects >
template<>
struct MD5Sum< ::extended_object_detection::SetSimpleObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::extended_object_detection::SetSimpleObjects >::value();
  }
  static const char* value(const ::extended_object_detection::SetSimpleObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::extended_object_detection::SetSimpleObjectsRequest> should match
// service_traits::DataType< ::extended_object_detection::SetSimpleObjects >
template<>
struct DataType< ::extended_object_detection::SetSimpleObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::extended_object_detection::SetSimpleObjects >::value();
  }
  static const char* value(const ::extended_object_detection::SetSimpleObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::extended_object_detection::SetSimpleObjectsResponse> should match
// service_traits::MD5Sum< ::extended_object_detection::SetSimpleObjects >
template<>
struct MD5Sum< ::extended_object_detection::SetSimpleObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::extended_object_detection::SetSimpleObjects >::value();
  }
  static const char* value(const ::extended_object_detection::SetSimpleObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::extended_object_detection::SetSimpleObjectsResponse> should match
// service_traits::DataType< ::extended_object_detection::SetSimpleObjects >
template<>
struct DataType< ::extended_object_detection::SetSimpleObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::extended_object_detection::SetSimpleObjects >::value();
  }
  static const char* value(const ::extended_object_detection::SetSimpleObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXTENDED_OBJECT_DETECTION_MESSAGE_SETSIMPLEOBJECTS_H
