// Generated by gencpp from file grasping_msgs/FindGraspableObjectsGoal.msg
// DO NOT EDIT!


#ifndef GRASPING_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H
#define GRASPING_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasping_msgs
{
template <class ContainerAllocator>
struct FindGraspableObjectsGoal_
{
  typedef FindGraspableObjectsGoal_<ContainerAllocator> Type;

  FindGraspableObjectsGoal_()
    : plan_grasps(false)  {
    }
  FindGraspableObjectsGoal_(const ContainerAllocator& _alloc)
    : plan_grasps(false)  {
  (void)_alloc;
    }



   typedef uint8_t _plan_grasps_type;
  _plan_grasps_type plan_grasps;





  typedef boost::shared_ptr< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FindGraspableObjectsGoal_

typedef ::grasping_msgs::FindGraspableObjectsGoal_<std::allocator<void> > FindGraspableObjectsGoal;

typedef boost::shared_ptr< ::grasping_msgs::FindGraspableObjectsGoal > FindGraspableObjectsGoalPtr;
typedef boost::shared_ptr< ::grasping_msgs::FindGraspableObjectsGoal const> FindGraspableObjectsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator1> & lhs, const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.plan_grasps == rhs.plan_grasps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator1> & lhs, const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasping_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4aadd364d1b04bf1e9e9fdbdce5637d4";
  }

  static const char* value(const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4aadd364d1b04bf1ULL;
  static const uint64_t static_value2 = 0xe9e9fdbdce5637d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasping_msgs/FindGraspableObjectsGoal";
  }

  static const char* value(const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"###########################################################\n"
"# This action is called for integrated object detection and\n"
"#  grasp planning, such as in base_grasping_perception\n"
"\n"
"# Set to false to disable grasp planning, returning only the objects found\n"
"bool plan_grasps\n"
;
  }

  static const char* value(const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan_grasps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindGraspableObjectsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator>& v)
  {
    s << indent << "plan_grasps: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_grasps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPING_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H
